name: OpenCADC
tagline: Astronomy like mum used to make, only better.
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
future: true
github_url: 'https://github.com/opencadc'
twitter_url: 'https://twitter.com/AstroCADC'
slack_url: '/slack'
repository: 'opencadc/opencadc.github.io'
organization_name: 'opencadc'
plugins:
  - jekyll-redirect-from

title: "OpenCADC "
description: Like the Astronomy your mum used to make, only better.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman